### ISSUE TITLE
Error while running event

### ISSUE THREAD

**Issue by dz9c92** [Daedeross/Subterra#5]
http://prntscr.com/k6hrc0
Happened when I died

**Comment by Daedeross** [comment]
Ah, this is not something I have tested yet. Thanks for the report.
I know what's causing this, it's the logic that transports players between levels when stepping over the stairs. Since you died you temporarily have no 'character' which I am not checking for nil in the script.
this will be fixed in the next update (0,4,0).
On related note, looks like this will also cause Sandbox games to crash.

**Comment by Daedeross** [comment]
Resolved in v 0.4.0
