### ISSUE TITLE
Unable to place entity "stair - down" due to a conflict

### ISSUE THREAD

**Issue by SimoMarr** [Daedeross/Subterra#6]
![screenshot 8](https://user-images.githubusercontent.com/39137118/42733191-596fb8de-882d-11e8-9b1d-db930377203b.png)
Hi everyone! The issue i encountered is in the title!
Putting a stair-down in random places and never placed one..
Can you please tell me what of my mods are in conflict?
Here's my mod list:

-Cargo Ships 0.0.9
-Compact Power 1.0.5
-Exoskeleton Mark II 3.0.0
-Item Giver Gui 0.0.8
-Logistic Research Fix 1.0.1
-Logtech Beacon 1.0.0
-NPUtils 0.3.30
-Pipes Fix 0.0.1
-Quarry 1.6.10
-Waterfill V15 0.1.3

and naturally Subterra 0.3.5

PS. : Until i get to place some stairs, everything is going with no issues.

**Comment by Daedeross** [comment]
I don't think it's another mod that's conflicting, though it might be, I'll have to test those.
That message usually means there is something in the way on the target layer, you are on the bottom layer, or on a non-supported surface (like inside a Factorissimo factory).
Since placing a stairs down also has places a stair up on the layer bellow, the target location has to be clear and if it's not you will get that message. If you load this mod into a big map that is already explored, it may take a few minutes for the chunk generation to catch up for the underground layers and there might be water below you at that moment which will eventually be cleared by the generation scripts.
